---
- name: Download
  get_url:
    dest: /tmp/pnpm-install.sh
    mode: 0755
    url: https://get.pnpm.io/install.sh

- name: Remove pnpm
  file:
    path: "{{ ansible_user_dir }}/.local/share/pnpm"
    state: absent

- name: Install pnpm
  shell: /tmp/pnpm-install.sh env PNPM_VERSION=8.0.0 sh -

- name: Remove pnpm Installation Script
  file:
    path: /tmp/pnpm-install.sh
    state: absent
